version: "3.8"
services:
  backend-manim:
    build:
      context: ./backend-manim
      dockerfile: Dockerfile  
    ports:
      - "10000:10000"
    volumes:
      - ./backend-manim:/app
    env_file:
      - .env  
         
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    env_file:
      - .env  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
        sh -c "npm install && npm run dev"

