version: "3.8"
services:
  backend-manim:
    build:
      context: ./backend-manim
      dockerfile: Dockerfile  
    ports:
      - "10000:10000"
    volumes:
      - ./backend-manim:/app
    env_file:
      - .env  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "6006:6006"
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
